use crate::{metadata::SessionMetadata, AppState};
use std::collections::HashSet;
use std::sync::Arc;

/// Computes the observation IDs that a background anti-spam trim must never
/// remove: IDs cited in evidence snapshots of recommendations in a state
/// where the user or the system has acted on the card (Accepted, Executing,
/// or a rolled-up member). A Proposed card is regenerated by the evaluator
/// from stored observations on each pass and carries its evidence as
/// embedded snapshots, so Proposed citations must not pin spam records
/// forever - that would defeat the trim for the common qualifying-spam case.
fn protected_observation_ids(workspace: &crate::WorkspaceState) -> Result<HashSet<String>, String> {
    let mut protected = HashSet::new();
    for recommendation in workspace
        .recommendation_store
        .list()
        .map_err(|error| error.to_string())?
    {
        let live = matches!(
            recommendation.status,
            crate::taskmaster::RecommendationStatus::Accepted
                | crate::taskmaster::RecommendationStatus::Executing
                | crate::taskmaster::RecommendationStatus::RolledUp
        );
        if live {
            for evidence in &recommendation.evidence {
                protected.insert(evidence.observation_id.clone());
            }
        }
    }
    Ok(protected)
}

/// Runs one pass of the observation anti-spam trim over the active
/// workspace. Returns the removed observation IDs. Called from the retention
/// cleanup loop so scan spam re-detected by Peon is trimmed on the same
/// 5-minute cadence as session retention.
pub(crate) fn observation_spam_cleanup_once(
    state: Arc<AppState>,
    now: chrono::DateTime<chrono::Utc>,
) -> Vec<String> {
    let ws_guard = state.workspace.lock().unwrap();
    let Some(ws) = ws_guard.as_ref() else {
        return Vec::new();
    };
    let protected = match protected_observation_ids(ws) {
        Ok(protected) => protected,
        Err(error) => {
            tracing::warn!(%error, "observation spam cleanup: could not list recommendations; skipping pass");
            return Vec::new();
        }
    };
    match ws
        .workflow_observations
        .trim_redundant_occurrences(now, &protected)
    {
        Ok(removed) => {
            if !removed.is_empty() {
                tracing::info!(
                    removed = removed.len(),
                    "observation spam cleanup: trimmed redundant occurrences"
                );
            }
            removed
        }
        Err(error) => {
            tracing::warn!(%error, "observation spam cleanup: trim pass failed");
            Vec::new()
        }
    }
}

pub(crate) fn delete_session_evidence(
    workspace: &crate::WorkspaceState,
    session_id: &str,
    mut delete_recommendations: impl FnMut(&str) -> Result<(), String>,
) -> Result<(), String> {
    workspace
        .workflow_observations
        .delete_session_observations(session_id)
        .map_err(|error| error.to_string())?;
    workspace
        .metadata
        .delete_events(session_id)
        .map_err(|error| error.to_string())?;
    workspace
        .metadata
        .clear_last_active_session_if_matches(session_id)
        .map_err(|error| error.to_string())?;
    workspace
        .metadata
        .delete_session(session_id)
        .map_err(|error| error.to_string())?;
    // Recommendation cleanup is last: if deleting the session metadata fails,
    // the session remains retryable and its evidence-backed recommendations
    // are preserved for that retry. Orphan cleanup handles the inverse case.
    if let Err(first_error) = delete_recommendations(session_id) {
        delete_recommendations(session_id).map_err(|retry_error| {
            format!("{first_error}; recommendation cleanup retry failed: {retry_error}")
        })?;
    }
    Ok(())
}

fn select_expired_candidates(
    candidates: &[SessionMetadata],
    cutoff: chrono::DateTime<chrono::Utc>,
    protected_ids: &HashSet<String>,
) -> Vec<String> {
    let mut ordered: Vec<&SessionMetadata> = candidates.iter().collect();
    ordered.sort_by(|a, b| a.last_activity.cmp(&b.last_activity));
    ordered
        .into_iter()
        .filter(|session| !protected_ids.contains(&session.id))
        .filter_map(|session| {
            chrono::DateTime::parse_from_rfc3339(&session.last_activity)
                .ok()
                .filter(|parsed| *parsed < cutoff)
                .map(|_| session.id.clone())
        })
        .collect()
}

fn select_count_candidates(
    candidates: &[SessionMetadata],
    max_sessions: usize,
    protected_ids: &HashSet<String>,
) -> Vec<String> {
    if max_sessions == 0 || candidates.len() <= max_sessions {
        return Vec::new();
    }

    let to_delete = candidates.len() - max_sessions;
    let mut ordered: Vec<&SessionMetadata> = candidates.iter().collect();
    ordered.sort_by(|a, b| a.last_activity.cmp(&b.last_activity));
    ordered
        .into_iter()
        .filter(|session| !protected_ids.contains(&session.id))
        .take(to_delete)
        .map(|session| session.id.clone())
        .collect()
}

pub(crate) async fn retention_cleanup_task(state: Arc<AppState>) {
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(300)).await;
        retention_cleanup_once(&state, chrono::Utc::now()).await;
        observation_spam_cleanup_once(state.clone(), chrono::Utc::now());
    }
}

pub(crate) async fn retention_cleanup_once(
    state: &Arc<AppState>,
    now: chrono::DateTime<chrono::Utc>,
) {
    let config = state.retention_config.read().await.clone();
    if config.max_sessions == 0 && config.max_age_days == 0 {
        return;
    }

    let all_sessions = {
        let ws_guard = state.workspace.lock().unwrap();
        match &*ws_guard {
            Some(ws) => ws.metadata.read_all_sessions(),
            None => return,
        }
    };

    let mut candidates: Vec<_> = all_sessions.into_iter().collect();

    if candidates.is_empty() {
        return;
    }

    candidates.sort_by(|a, b| a.last_activity.cmp(&b.last_activity));

    let mut all_deleted: Vec<String> = Vec::new();

    if config.max_age_days > 0 {
        let cutoff = now - chrono::Duration::days(config.max_age_days as i64);
        let expired = select_expired_candidates(&candidates, cutoff, &HashSet::new());
        if !expired.is_empty() {
            let mut deleted_expired = Vec::new();
            let ws_guard = state.workspace.lock().unwrap();
            if let Some(ref ws) = *ws_guard {
                let mut sessions = state.sessions.lock().unwrap();
                for id in &expired {
                    if sessions.get(id).is_some_and(|h| {
                        h.info.status == "live"
                            || h.info.status == "creating"
                            || h.info.status == "running"
                    }) {
                        continue;
                    }
                    tracing::info!(session_id = %id, "retention: deleting expired session");
                    if let Err(error) = delete_session_evidence(ws, id, |session_id| {
                        ws.recommendation_store
                            .delete_referencing_session(session_id)
                            .map_err(|error| error.to_string())
                    }) {
                        tracing::error!(session_id = %id, %error, "retention: failed to delete expired session");
                        if !ws.metadata.session_file_exists(id) {
                            sessions.remove(id);
                            deleted_expired.push(id.clone());
                        }
                        continue;
                    }
                    sessions.remove(id);
                    deleted_expired.push(id.clone());
                }
            }
            all_deleted.extend(deleted_expired.iter().cloned());
            candidates.retain(|s| !deleted_expired.contains(&s.id));
        }
    }

    if config.max_sessions > 0 && candidates.len() > config.max_sessions {
        let ws_guard = state.workspace.lock().unwrap();
        if let Some(ref ws) = *ws_guard {
            let mut sessions = state.sessions.lock().unwrap();
            let protected_ids = sessions
                .iter()
                .filter(|(_, handle)| {
                    handle.info.status == "live"
                        || handle.info.status == "creating"
                        || handle.info.status == "running"
                })
                .map(|(id, _)| id.clone())
                .collect();
            let eligible =
                select_count_candidates(&candidates, config.max_sessions, &protected_ids);
            for id in eligible {
                if sessions.get(&id).is_some_and(|h| {
                    h.info.status == "live"
                        || h.info.status == "creating"
                        || h.info.status == "running"
                }) {
                    continue;
                }
                tracing::info!(
                    session_id = %id,
                    max_sessions = config.max_sessions,
                    "retention: deleting session (exceeds max)"
                );
                if let Err(error) = delete_session_evidence(ws, &id, |session_id| {
                    ws.recommendation_store
                        .delete_referencing_session(session_id)
                        .map_err(|error| error.to_string())
                }) {
                    tracing::error!(session_id = %id, %error, "retention: failed to delete session");
                    if !ws.metadata.session_file_exists(&id) {
                        sessions.remove(&id);
                        all_deleted.push(id);
                    }
                    continue;
                }
                sessions.remove(&id);
                all_deleted.push(id);
            }
        }
    }

    if !all_deleted.is_empty() {
        let mut peon_output = state.peon.last_output.write().unwrap();
        let mut peon_inference = state.peon.last_inference.write().unwrap();
        for id in &all_deleted {
            peon_output.remove(id);
            peon_inference.remove(id);
        }
        drop(peon_inference);
        drop(peon_output);
        for id in &all_deleted {
            crate::session_application::SessionApplication::new(state.clone())
                .clear_forgotten_session_tracking(id);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::metadata;
    use crate::test_support::*;
    use crate::workflow_observations::{
        Impact, ObservationCandidate, ObservationKind, ObservationOrigin,
    };
    use std::collections::HashSet;
    use std::fs;

    fn retention_test_session(id: &str, last_activity: &str) -> metadata::SessionMetadata {
        test_session_metadata(
            id,
            id,
            "/tmp/orkworks-retention-tests",
            "ended",
            last_activity,
            last_activity,
        )
    }

    fn spam_observation_key(index: usize) -> String {
        format!("spam-{index}")
    }

    fn record_spam_hits(
        store: &crate::workflow_observations::WorkflowObservationStore,
        session_id: &str,
        count: usize,
    ) {
        let base = chrono::Utc::now();
        for index in 0..count {
            store.test_set_clock(base + chrono::Duration::minutes(index as i64 * 10));
            store
                .record_observation(
                    session_id,
                    ObservationOrigin::Peon,
                    &spam_observation_key(index),
                    ObservationCandidate {
                        kind: ObservationKind::Obstacle,
                        description: "model detection".into(),
                        evidence: format!("evidence {index}"),
                        problem_area: None,
                        reported_impact: Impact::Medium,
                        confidence: Some(0.8),
                    },
                )
                .unwrap();
        }
    }

    #[test]
    fn observation_spam_cleanup_protects_cited_ids_and_trims_the_rest() {
        let dir = tempfile::tempdir().unwrap();
        let state = test_app_state_with_workspace(dir.path());
        let cited_id = {
            let ws_guard = state.workspace.lock().unwrap();
            let ws = ws_guard.as_ref().unwrap();

            record_spam_hits(&ws.workflow_observations, "session-a", 4);
            let observations = ws.workflow_observations.workspace_observations().unwrap();
            let middle = observations[1].id.clone();

            // An accepted recommendation cites the second hit: its ID must
            // survive the cleanup pass, while the uncited hit after it
            // (within the spam window of a kept predecessor) is trimmed.
            let recommendation = test_recommendation_with_evidence_ids(
                "rec-1",
                vec![middle.clone()],
                crate::taskmaster::RecommendationStatus::Accepted,
            );
            ws.recommendation_store.put(&recommendation).unwrap();
            middle
        };

        let removed = observation_spam_cleanup_once(state.clone(), chrono::Utc::now());

        let ws_guard = state.workspace.lock().unwrap();
        let ws = ws_guard.as_ref().unwrap();
        let remaining = ws.workflow_observations.workspace_observations().unwrap();
        // First, the protected second hit, and the latest survive; only the
        // uncited third hit is trimmed.
        assert_eq!(remaining.len(), 3);
        assert_eq!(removed.len(), 1);
        assert!(remaining.iter().any(|o| o.id == cited_id));
        assert!(removed
            .iter()
            .all(|id| !remaining.iter().any(|o| o.id == *id)));
    }

    #[test]
    fn observation_spam_cleanup_trims_hits_cited_by_proposed_recommendations() {
        // A Proposed card is regenerated by the evaluator from stored
        // observations each pass and carries its evidence as embedded
        // snapshots, so citations in Proposed evidence must not pin spam
        // records forever - that would defeat the trim for the common
        // qualifying-spam case.
        let dir = tempfile::tempdir().unwrap();
        let state = test_app_state_with_workspace(dir.path());
        let cited_id = {
            let ws_guard = state.workspace.lock().unwrap();
            let ws = ws_guard.as_ref().unwrap();

            record_spam_hits(&ws.workflow_observations, "session-a", 3);
            let observations = ws.workflow_observations.workspace_observations().unwrap();
            let middle = observations[1].id.clone();
            let recommendation = test_recommendation_with_evidence_ids(
                "rec-1",
                vec![middle.clone()],
                crate::taskmaster::RecommendationStatus::Proposed,
            );
            ws.recommendation_store.put(&recommendation).unwrap();
            middle
        };

        let removed = observation_spam_cleanup_once(state.clone(), chrono::Utc::now());

        let ws_guard = state.workspace.lock().unwrap();
        let ws = ws_guard.as_ref().unwrap();
        let remaining = ws.workflow_observations.workspace_observations().unwrap();
        assert_eq!(remaining.len(), 2);
        assert!(removed.contains(&cited_id));
    }

    #[test]
    fn observation_spam_cleanup_continues_after_one_session_rewrite_fails() {
        let dir = tempfile::tempdir().unwrap();
        let state = test_app_state_with_workspace(dir.path());
        {
            let ws_guard = state.workspace.lock().unwrap();
            let ws = ws_guard.as_ref().unwrap();
            record_spam_hits(&ws.workflow_observations, "session-a", 3);
            record_spam_hits(&ws.workflow_observations, "session-b", 3);
            // Make session-b's segment impossible to atomically replace.
            let broken = dir
                .path()
                .join(".orkworks-test")
                .join("workflow-observations")
                .join("session-b.ndjson");
            fs::remove_file(&broken).unwrap();
            fs::create_dir(&broken).unwrap();
        }

        let removed = observation_spam_cleanup_once(state.clone(), chrono::Utc::now());

        // session-a was trimmed despite session-b's rewrite failing.
        let ws_guard = state.workspace.lock().unwrap();
        let ws = ws_guard.as_ref().unwrap();
        let remaining_a = ws
            .workflow_observations
            .session_observations("session-a")
            .unwrap();
        let remaining_b = ws
            .workflow_observations
            .session_observations("session-b")
            .unwrap();
        assert_eq!(remaining_a.len(), 2);
        assert_eq!(remaining_b.len(), 3);
        assert_eq!(removed.len(), 1);
    }

    #[test]
    fn expired_candidates_ignore_invalid_timestamps_and_protected_sessions() {
        let candidates = vec![
            retention_test_session("newest", "2024-01-10T00:00:00Z"),
            retention_test_session("invalid", "not-a-timestamp"),
            retention_test_session("protected", "2024-01-02T00:00:00Z"),
            retention_test_session("oldest", "2024-01-01T00:00:00Z"),
        ];
        let protected = HashSet::from(["protected".to_string()]);
        let cutoff = chrono::DateTime::parse_from_rfc3339("2024-01-05T00:00:00Z")
            .unwrap()
            .with_timezone(&chrono::Utc);

        assert_eq!(
            select_expired_candidates(&candidates, cutoff, &protected),
            vec!["oldest"]
        );
    }

    #[test]
    fn count_candidates_select_oldest_eligible_sessions_only() {
        let candidates = vec![
            retention_test_session("newest", "2024-01-04T00:00:00Z"),
            retention_test_session("middle", "2024-01-03T00:00:00Z"),
            retention_test_session("protected", "2024-01-02T00:00:00Z"),
            retention_test_session("oldest", "2024-01-01T00:00:00Z"),
        ];
        let protected = HashSet::from(["protected".to_string()]);

        assert_eq!(
            select_count_candidates(&candidates, 2, &protected),
            vec!["oldest", "middle"]
        );
    }

    #[test]
    fn count_selection_can_run_after_age_candidates_are_removed() {
        let remaining = vec![
            retention_test_session("newer", "2024-01-04T00:00:00Z"),
            retention_test_session("oldest-remaining", "2024-01-03T00:00:00Z"),
        ];

        assert_eq!(
            select_count_candidates(&remaining, 1, &HashSet::new()),
            vec!["oldest-remaining"]
        );
    }

    fn record_test_observation(
        store: &crate::workflow_observations::WorkflowObservationStore,
        session_id: &str,
        key: &str,
    ) {
        store
            .record_observation(
                session_id,
                ObservationOrigin::Agent,
                key,
                ObservationCandidate {
                    kind: ObservationKind::VerificationGap,
                    description: "test observation".into(),
                    evidence: "test evidence".into(),
                    problem_area: None,
                    reported_impact: Impact::Low,
                    confidence: None,
                },
            )
            .unwrap();
    }

    #[test]
    fn delete_session_evidence_removes_only_one_session_and_preserves_sequence() {
        let dir = tempfile::tempdir().unwrap();
        let state = test_app_state_with_workspace(dir.path());
        let ws_guard = state.workspace.lock().unwrap();
        let ws = ws_guard.as_ref().unwrap();
        for id in ["session-a", "session-b"] {
            ws.metadata.write_session(&test_session_metadata(
                id,
                id,
                dir.path().display().to_string(),
                "ended",
                "2024-01-01T00:00:00Z",
                "2024-01-01T00:00:00Z",
            ));
            ws.metadata
                .append_terminal_output_lines(id, &["terminal".into()]);
            record_test_observation(&ws.workflow_observations, id, id);
        }
        ws.metadata
            .write_workspace_memory(&metadata::WorkspaceMemory {
                last_active_session_id: Some("session-a".into()),
                last_active_at: Some("2024-01-01T00:00:00Z".into()),
                active_harness_ids: vec![],
                active_harness_revision: 0,
            });

        delete_session_evidence(ws, "session-a", |_| Ok(())).unwrap();

        assert!(!ws.metadata.session_file_exists("session-a"));
        assert!(ws.metadata.read_session("session-b").is_some());
        assert!(ws.metadata.read_terminal_output("session-a", 10).is_empty());
        assert_eq!(
            ws.workflow_observations
                .workspace_observations()
                .unwrap()
                .len(),
            1
        );
        assert_eq!(
            ws.workflow_observations.workspace_observations().unwrap()[0].session_id,
            "session-b"
        );
        record_test_observation(&ws.workflow_observations, "session-b", "after-delete");
        assert_eq!(
            ws.workflow_observations.workspace_observations().unwrap()[1].sequence,
            3
        );
    }

    #[test]
    fn delete_session_evidence_keeps_recommendations_retryable_when_cleanup_fails() {
        let dir = tempfile::tempdir().unwrap();
        let state = test_app_state_with_workspace(dir.path());
        let ws_guard = state.workspace.lock().unwrap();
        let ws = ws_guard.as_ref().unwrap();
        ws.metadata.write_session(&test_session_metadata(
            "session-a",
            "session-a",
            dir.path().display().to_string(),
            "ended",
            "2024-01-01T00:00:00Z",
            "2024-01-01T00:00:00Z",
        ));
        record_test_observation(&ws.workflow_observations, "session-a", "session-a");

        let result =
            delete_session_evidence(ws, "session-a", |_| Err("recommendations failed".into()));

        assert_eq!(
            result.unwrap_err(),
            "recommendations failed; recommendation cleanup retry failed: recommendations failed"
        );
        // The metadata deletion completed before the failing final cleanup;
        // the recommendation remains available for orphan cleanup/retry, and
        // the session is no longer intact.
        assert!(!ws.metadata.session_file_exists("session-a"));
        assert_eq!(
            ws.workflow_observations
                .workspace_observations()
                .unwrap()
                .len(),
            0
        );
    }

    #[test]
    fn delete_session_evidence_reports_observation_cleanup_failure() {
        let dir = tempfile::tempdir().unwrap();
        let state = test_app_state_with_workspace(dir.path());
        let ws_guard = state.workspace.lock().unwrap();
        let ws = ws_guard.as_ref().unwrap();
        ws.metadata.write_session(&test_session_metadata(
            "session-a",
            "session-a",
            dir.path().display().to_string(),
            "ended",
            "2024-01-01T00:00:00Z",
            "2024-01-01T00:00:00Z",
        ));
        record_test_observation(&ws.workflow_observations, "session-a", "session-a");
        let segment_path = dir
            .path()
            .join(".orkworks-test/workflow-observations/session-a.ndjson");
        std::fs::remove_file(&segment_path).unwrap();
        std::fs::create_dir(&segment_path).unwrap();

        let result = delete_session_evidence(ws, "session-a", |_| Ok(()));

        assert!(result.is_err());
        assert!(ws.metadata.session_file_exists("session-a"));
    }

    #[tokio::test]
    async fn retention_cleanup_keeps_live_sessions() {
        let dir = tempfile::tempdir().unwrap();
        let state = test_app_state_with_workspace(dir.path());
        let session_id = "still-live".to_string();

        {
            let ws_guard = state.workspace.lock().unwrap();
            let ws = ws_guard.as_ref().unwrap();
            ws.metadata.write_session(&test_session_metadata(
                session_id.clone(),
                "Still Live",
                dir.path().display().to_string(),
                "ended",
                "2024-01-01T00:00:00Z",
                "2024-01-01T00:00:00Z",
            ));
        }

        let (kill_tx, _) = tokio::sync::watch::channel(false);
        state.sessions.lock().unwrap().insert(
            session_id.clone(),
            crate::SessionHandle {
                info: test_session_info(
                    session_id.clone(),
                    "Still Live",
                    dir.path().display().to_string(),
                    "running",
                    "2024-01-01T00:00:00Z",
                ),
                kill_tx,
                output_buffer: crate::peon::RingBuffer::new(200),
                scan_buf: String::new(),
                pending_work_signal: None,
                runtime: crate::runtime::session_runtime::SessionRuntime::detached(
                    crate::runtime::session_runtime::DEFAULT_TERMINAL_ROWS,
                    crate::runtime::session_runtime::DEFAULT_TERMINAL_COLS,
                ),
                terminal_attached: false,
                resume_in_progress: false,
                capacity: crate::capacity_state::CapacityState::default(),
                active_work_hook: false,
            },
        );

        {
            let mut config = state.retention_config.write().await;
            config.max_age_days = 1;
            config.max_sessions = 0;
        }

        retention_cleanup_once(&state, chrono::Utc::now()).await;

        let ws_guard = state.workspace.lock().unwrap();
        let ws = ws_guard.as_ref().unwrap();
        assert!(ws.metadata.read_session(&session_id).is_some());
    }

    #[tokio::test]
    async fn retention_cleanup_clears_last_active_when_session_is_deleted() {
        let dir = tempfile::tempdir().unwrap();
        let state = test_app_state_with_workspace(dir.path());
        let session_id = "old-session".to_string();

        {
            let ws_guard = state.workspace.lock().unwrap();
            let ws = ws_guard.as_ref().unwrap();
            ws.metadata.write_session(&test_session_metadata(
                session_id.clone(),
                "Old Session",
                dir.path().display().to_string(),
                "ended",
                "2024-01-01T00:00:00Z",
                "2024-01-01T00:00:00Z",
            ));
            ws.metadata
                .write_workspace_memory(&metadata::WorkspaceMemory {
                    last_active_session_id: Some(session_id.clone()),
                    last_active_at: Some("2024-01-01T00:00:00Z".into()),
                    active_harness_ids: vec![],
                    active_harness_revision: 0,
                });
        }

        state
            .peon
            .label_epochs
            .write()
            .unwrap()
            .insert(session_id.clone(), 2);

        {
            let mut config = state.retention_config.write().await;
            config.max_age_days = 1;
            config.max_sessions = 0;
        }

        let now = chrono::DateTime::parse_from_rfc3339("2024-02-01T00:00:00Z")
            .unwrap()
            .with_timezone(&chrono::Utc);
        retention_cleanup_once(&state, now).await;

        let ws_guard = state.workspace.lock().unwrap();
        let ws = ws_guard.as_ref().unwrap();
        assert!(ws.metadata.read_session(&session_id).is_none());
        let memory = ws.metadata.read_workspace_memory().unwrap();
        assert_eq!(memory.last_active_session_id, None);
        assert_eq!(memory.last_active_at, None);
        assert!(!state
            .peon
            .label_epochs
            .read()
            .unwrap()
            .contains_key(&session_id));
    }
}
